# Generated by Django 2.1.7 on 2019-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
