# Generated by Django 2.1.7 on 2019-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Path', '0002_auto_20190331_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
