# Generated by Django 2.1.7 on 2019-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Path', '0003_auto_20190331_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='lng',
            field=models.CharField(max_length=100),
        ),
    ]
