# Generated by Django 2.1.7 on 2019-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Path', '0004_auto_20190401_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='lng',
            field=models.IntegerField(),
        ),
    ]
